\set ON_ERROR_STOP on
\connect users

\echo
\echo [users] Configure DB owner, extensions and privileges

ALTER DATABASE users OWNER TO users_owner;
CREATE EXTENSION IF NOT EXISTS pgcrypto;

REVOKE ALL ON SCHEMA public FROM PUBLIC;
GRANT USAGE, CREATE ON SCHEMA public TO users_owner;
ALTER SCHEMA public OWNER TO users_owner;


GRANT CONNECT ON DATABASE users TO svc_users;
GRANT USAGE ON SCHEMA public TO svc_users;


GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO svc_users;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO svc_users;


ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO svc_users;
ALTER DEFAULT PRIVILEGES IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO svc_users;


ALTER DEFAULT PRIVILEGES FOR ROLE users_owner IN SCHEMA public
  GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO svc_users;
ALTER DEFAULT PRIVILEGES FOR ROLE users_owner IN SCHEMA public
  GRANT USAGE, SELECT ON SEQUENCES TO svc_users;

\echo [users] Done.
